name             'irb'
maintainer       'Wanelo'
maintainer_email 'ops@wanelo.com'
license          'MIT'
description      'Installs/Configures irb'
long_description 'Installs/Configures irb'
version          '0.1.0'
